name: Build

on:
  push:
  schedule:
    - cron: "5 1 * * *" # Run nightly
  workflow_dispatch:

jobs:
  build:
    name: Building the player
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6.0.1
      - uses: actions/setup-node@v6.1.0
        with:
          node-version: 20.20.2

      - name: make clean
        run: make clean

      - name: make init
        run: make init

      - name: make build
        run: make build