on:
  push:
    branches:
      - master
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://git@github.com:podigee/podigee-podcast-player.git"
          source_branch: "master"
          destination_repo: "git@github.com:podigee/podigee-podcast-player-internal.git"
          destination_branch: "master"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          # source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }}
          # destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} \